{
  "openapi": "3.1.0",
  "info": {
    "title": "io-protean",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "kyc"
    },
    {
      "name": "bank"
    }
  ],
  "paths": {
    "/api/v1/bank-account-validation/bank-validateacct": {
      "post": {
        "summary": "Bank Account Verification ",
        "deprecated": false,
        "description": "Verifies Bank Account through Penny Drop, PennyLess and Hybrid.",
        "operationId": "verifyBankAccount",
        "tags": [
          "kyc",
          "bank"
        ],
        "parameters": [
          {
            "name": "apikey",
            "in": "header",
            "description": "",
            "required": true,
            "example": "kidNaidREXqRUp9qPsrJcLC1pbYJ7Y0q97dFw3gHTf2gbXQF",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "content-type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "entityId": {
                    "type": "string",
                    "description": "Pre-configured constant values for different environements"
                  },
                  "programId": {
                    "type": "string",
                    "description": "Program id related to this activity. (310 for penny drop)"
                  },
                  "requestId": {
                    "type": "string",
                    "description": "Unique, alphanumeric reference\nnumber. Logic in pre-processing script.\n"
                  },
                  "txnType": {
                    "type": "string",
                    "description": "Defines mode of validation Options: ANY/ IMPS/\nNACH /UPI/ REVERSE/\nREVERSE_INTENT"
                  },
                  "custName": {
                    "type": "string",
                    "description": "Name of account holder to validate."
                  },
                  "custIfsc": {
                    "type": "string",
                    "description": "IFSC of bank account to validate. Required if\ntxnType is other than UPl/ REVERSE\n/ REVERSE_INTENT"
                  },
                  "custAcctNo": {
                    "type": "string",
                    "description": "Account number to validate. Required if txnType is\nother than UPl/ REVERSE\n/ REVERSE_INTENT"
                  },
                  "custVpa": {
                    "type": "string",
                    "description": "VPA to validate if txnType is UPI\nNot Required when txnType=REVERSE_INTENT"
                  },
                  "custMobileNo": {
                    "type": "string",
                    "description": "Mobile number\nRequired if txnType=UPI and VPA is provided."
                  },
                  "trackingRefNo": {
                    "type": "string",
                    "description": "Your system reference number for this user"
                  },
                  "callbackUrl": {
                    "type": "string",
                    "description": "The API endpoint where we will submit updates on\nthe validation status for each requestld.\nRequired if txnType is REVERSE/\nREVERSE_INTENT"
                  }
                },
                "required": [
                  "programId",
                  "requestId",
                  "txnType",
                  "entityId"
                ]
              },
              "example": {
                "entityId": "78bea7b4-1caf-4528-96e4-ec7f9f43f0db",
                "programId": "310",
                "requestId": "{{requestId}}",
                "custIfsc": "SBIN0061411",
                "custAcctNo": "42090969996",
                "txnType": "ANY"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "acValidationStatus": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "requestId": {
                      "type": "string"
                    },
                    "responseId": {
                      "type": "string"
                    },
                    "nameAtBank": {
                      "type": "string"
                    },
                    "custAcctNo": {
                      "type": "string"
                    },
                    "custIfsc": {
                      "type": "string"
                    },
                    "bankCode": {
                      "type": "string"
                    },
                    "methodUsed": {
                      "type": "string"
                    },
                    "custName": {
                      "type": "string"
                    },
                    "custVpa": {
                      "type": "string"
                    },
                    "fuzzylogicScore": {
                      "type": "string"
                    },
                    "utr": {
                      "type": "string"
                    },
                    "qrUrlString": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "statusCode"
                  ]
                },
                "example": {
                  "statusCode": "TB000",
                  "status": "ACCEPTED",
                  "acValidationStatus": "ACCOUNT_VALID",
                  "message": "SUCCESS",
                  "requestId": "eLsgw8yiUQpY30586637",
                  "responseId": "RES0ELSGW8YIUQPY30586637",
                  "nameAtBank": "Mr. Kaival Hemanshu Mehta",
                  "custAcctNo": "42090969996",
                  "custIfsc": "SBIN0061411",
                  "bankCode": "ESBZ",
                  "methodUsed": "IMPS_PENNY_DROP"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ],
        "x-sandbox-client-name": "Protean"
      }
    }
  },
  "webhooks": {},
  "components": {
    "schemas": {},
    "responses": {
      "Forbidden": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "message": {
                  "type": "string"
                },
                "timestamp": {
                  "type": "integer"
                },
                "transaction_id": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "message",
                "timestamp",
                "transaction_id"
              ]
            },
            "examples": {
              "Example 1": {
                "summary": "Example 1",
                "value": {
                  "code": 403,
                  "message": "Insufficient privilege",
                  "timestamp": 1769086379555,
                  "transaction_id": "2e918bdd-2d06-411b-b1a4-c20c95149737"
                }
              }
            }
          }
        }
      },
      "Unauthorized": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer"
                },
                "message": {
                  "type": "string"
                },
                "timestamp": {
                  "type": "integer"
                },
                "transaction_id": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "message",
                "timestamp",
                "transaction_id"
              ]
            },
            "examples": {
              "Example 1": {
                "summary": "Example 1",
                "value": {
                  "code": 401,
                  "message": "Unauthorized",
                  "timestamp": 1769086427379,
                  "transaction_id": "ccfc9b5a-bdd1-4baf-9a9a-443b603225cf"
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [],
  "security": []
}